apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-deployment
  labels:
    app: online
spec:
  replicas: 2
  selector:
    matchLabels:
      app: online
  template:
    metadata:
      labels:
        app: online
    spec:
      containers:
      - name: online
        image: dharanisony2002/docker
        ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: online-service
spec:
  selector:
    app: online
  ports:
    - protocol: TCP
      port: 8080         # Exposed port on the LoadBalancer
      targetPort: 8081   # Port your container is listening on
  type: LoadBalancer     # External access
